### ISSUE TITLE
Potentially Wrong Answer?

### ISSUE THREAD

**Issue by attilavago** [robfentress/was-practice#32]
In https://github.com/robfentress/was-practice/blob/master/I/A/1.a.gift on line 270, I believe the correct answer might be wrong:

```
// [2.4.3 (Focus Order)](http://www.w3.org/WAI/WCAG20/quickref/20160105/#navigation-mechanisms-focus-order)

Ensuring focusable components receive focus in an order that preserves meaning and operability is an example of which accessibility principle?
{
  =Perceivable
  ~Operable
  ~Understandable
  ~Robust
}
```
If it's 2.4.3, does that not mean that according to https://www.w3.org/WAI/WCAG21/quickref/ it falls under **"Operable"** rather than **"Perceivable"**?

**Comment by robfentress** [comment]
Thanks for the catch.  I've corrected it.
